package Overnet::Burner::RexBundle;

use strictures 2;

use Carp       qw(croak);
use File::Path qw(make_path);
use File::Spec;
use JSON ();

use Overnet::Burner::Util qw(clone_json json_text write_file);

our $VERSION = '0.001';

my @ROLE_FIELDS      = qw(relays publishers subscribers query_readers object_readers observers);
my @LIFECYCLE_PHASES = qw(bootstrap deploy start warmup run chaos collect cleanup);

sub render {
  my ($class, %args) = @_;

  my $run_dir = $args{run_dir} || croak "run_dir is required\n";
  my $plan    = $args{plan}    || croak "plan is required\n";
  if (!-d $run_dir) {
    croak "run_dir does not exist: $run_dir\n";
  }

  my $relative_dir = File::Spec->catdir('artifacts', 'rex');
  my $bundle_dir   = File::Spec->catdir($run_dir,    $relative_dir);
  my @actors       = _actors($plan);
  my %content      = (
    'Rexfile'                  => _rexfile($plan),
    'actor-hosts.json'         => _json(_actor_hosts(\@actors)),
    'artifact-collection.json' => _json(_artifact_collection($plan)),
    'chaos-hooks.json'         => _json({hooks => _clone($plan->{chaos_hooks} || [])}),
    'inventory/hosts.json'     => _json(_inventory(\@actors)),
    'lifecycle.json'           => _json(_lifecycle()),
    'topology-provider.json'   => _json(_topology_provider($plan)),
  );

  for my $actor (@actors) {
    $content{File::Spec->catfile('actors', "$actor->{id}.json")} = _json(_actor_config($plan, $actor));
  }

  my @files = sort keys %content;
  $content{'bundle.json'} = _json(_bundle_index($plan, \@files));
  @files                  = sort keys %content;
  $content{'bundle.json'} = _json(_bundle_index($plan, \@files));

  make_path($bundle_dir, File::Spec->catdir($bundle_dir, 'actors'), File::Spec->catdir($bundle_dir, 'inventory'),);

  for my $relative_path (@files) {
    _write_file(File::Spec->catfile($bundle_dir, $relative_path), $content{$relative_path},);
  }

  return {
    relative_dir => $relative_dir,
    files        => \@files,
  };
}

sub _actors {
  my ($plan) = @_;
  my @actors;

  for my $field (@ROLE_FIELDS) {
    push @actors, @{$plan->{$field} || []};
  }

  return @actors;
}

sub _rexfile {
  my ($plan) = @_;

  my @groups = ('all', @ROLE_FIELDS);
  my $text   = <<'REX';
# Generated by overnet-burner Rex bundle renderer.
# Rendering this bundle does not perform remote execution.

use strictures 2;

use Rex -feature => ['1.4'];

REX

  for my $group (@groups) {
    $text .= "group '$group' => 'localhost';\n";
  }

  $text .= "\n";
  for my $phase (@LIFECYCLE_PHASES) {
    $text .= <<"REX";
task '$phase', sub {
    print "planned overnet-burner phase: $phase\\n";
};

REX
  }

  return $text;
}

sub _inventory {
  my ($actors) = @_;
  my %groups = map { $_ => [] } ('all', @ROLE_FIELDS);

  if (@{$actors}) {
    push @{$groups{all}}, 'host-001';
  }
  for my $field (@ROLE_FIELDS) {
    my $role = _field_role($field);
    if (_has_actor_role($actors, $role)) {
      push @{$groups{$field}}, 'host-001';
    }
  }

  return {
    groups => \%groups,
    hosts  => [
      {
        id       => 'host-001',
        hostname => 'localhost',
      },
    ],
  };
}

sub _actor_hosts {
  my ($actors) = @_;

  return {assignments => [map { {actor_id => $_->{id}, host_id => 'host-001', role => $_->{role},} } @{$actors}],};
}

sub _actor_config {
  my ($plan, $actor) = @_;

  return {
    actor   => _clone($actor),
    env     => _actor_env($plan, $actor),
    host_id => 'host-001',
    exists $actor->{metric_stream} ? (metric_stream => $actor->{metric_stream}) : (),
  };
}

sub _actor_env {
  my ($plan, $actor) = @_;

  return {
    OVERNET_BURNER_ACTOR_ID          => $actor->{id},
    OVERNET_BURNER_ROLE              => $actor->{role},
    OVERNET_BURNER_RUN_NAME          => $plan->{run}{name},
    OVERNET_BURNER_SEED              => "$actor->{seed}",
    OVERNET_BURNER_TOPOLOGY_PROVIDER => $plan->{topology_provider}{name},
  };
}

sub _lifecycle {
  my @commands;
  my $ordinal = 0;

  for my $phase (@LIFECYCLE_PHASES) {
    $ordinal++;
    push @commands,
      {
      id        => sprintf('lifecycle-%03d', $ordinal),
      execution => 'planned',
      phase     => $phase,
      rex_task  => $phase,
      };
  }

  return {commands => \@commands};
}

sub _topology_provider {
  my ($plan) = @_;

  return {
    topology_provider => _clone($plan->{topology_provider} || {}),
    relays            => [map { _topology_provider_relay($_) } @{$plan->{relays} || []},],
  };
}

sub _topology_provider_relay {
  my ($relay) = @_;

  my $relay_record = {actor_id => $relay->{id},};
  my $descriptor   = $relay->{topology_provider_descriptor} || {};
  my $command      = $descriptor->{command};
  if ($command) {
    $relay_record->{lifecycle} = {
      health => {
        command   => $command->{health},
        execution => 'planned',
      },
      start => {
        command   => $command->{start},
        execution => 'planned',
      },
      stop => {
        command   => $command->{stop},
        execution => 'planned',
      },
    };
  }

  return $relay_record;
}

sub _has_actor_role {
  my ($actors, $role) = @_;

  for my $actor (@{$actors}) {
    if ($actor->{role} eq $role) {
      return 1;
    }
  }

  return 0;
}

sub _artifact_collection {
  my ($plan) = @_;

  return {
    files => [
      {
        id     => 'runner-log',
        source => 'logs/runner.jsonl',
      },
      {
        id     => 'metrics',
        source => 'metrics.jsonl',
      },
    ],
    metric_streams => _clone($plan->{metric_streams} || []),
  };
}

sub _bundle_index {
  my ($plan, $files) = @_;

  return {
    bundle => {
      name    => 'overnet-burner-rex',
      version => 1,
    },
    execution => {
      remote_execution => 'not_performed',
    },
    files       => $files,
    source_plan => {
      path         => 'plan.json',
      plan_version => $plan->{plan_version},
      scenario     => $plan->{scenario}{name},
    },
  };
}

sub _field_role {
  my ($field) = @_;

  my %role = (
    relays         => 'relay',
    publishers     => 'publisher',
    subscribers    => 'subscriber',
    query_readers  => 'query_reader',
    object_readers => 'object_reader',
    observers      => 'observer',
  );

  return $role{$field};
}

sub _json {
  my ($value) = @_;

  return json_text($value);
}

sub _clone {
  my ($value) = @_;

  return clone_json($value);
}

sub _write_file {
  my ($path, $content) = @_;

  write_file($path, $content);
  return;
}

1;

=head1 NAME

Overnet::Burner::RexBundle - Rex execution bundle renderer

=head1 DESCRIPTION

Renders deterministic Rex bundle artifacts for an overnet-burner execution plan.

=head1 VERSION

Version 0.001.

=head1 SYNOPSIS

  my $bundle = Overnet::Burner::RexBundle->render(%args);

=head1 SUBROUTINES/METHODS

=head2 render

=head1 DIAGNOSTICS

Missing run directories or invalid arguments are reported through exceptions.

=head1 CONFIGURATION AND ENVIRONMENT

No environment configuration is required for rendering.

=head1 DEPENDENCIES

See the distribution metadata for runtime dependencies.

=head1 INCOMPATIBILITIES

No known incompatibilities are documented.

=head1 BUGS AND LIMITATIONS

No known bugs are documented.

=head1 AUTHOR

Overnet Project.

=head1 LICENSE AND COPYRIGHT

See the project license.

=cut
